### ISSUE TITLE
uninitialized constant Error

### ISSUE THREAD

**Issue by sayakahojo** [Codezerker/apns_gatling#7]
I found out that uninitialized constant is used in the script below.

https://github.com/Codezerker/apns_gatling/blob/master/lib/apns_gatling/apns_client.rb#L85
https://github.com/Codezerker/apns_gatling/blob/master/lib/apns_gatling/apns_client.rb#L89

`uninitialized constant ApnsGatling::Client::ConnectionClosed`
`uninitialized constant ApnsGatling::Client::StreamLimitExceeded`

Please check this out.

**Comment by cloudorz** [comment]
@sayakahojo 
Thank you for issued this error. 
It was my stupid mistake. It fixed in latest version.
